.\" ukui-wm manual page.
.\" (C) 2000 Miguel de Icaza (miguel@helixcode.com)
.\" (C) 2009-2010 Vincent Untz (vuntz@gnome.org)
.\" (C) 2016, Tianjin KYLIN Information Technology Co., Ltd.
.\"
.TH UKUI-WM 1 "11 February 2016" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
ukui-wm \- Start the window manager configured by the user
.SH "SYNOPSIS"
.PP
.B ukui-wm [--default-wm=WINDOWMANAGER] [--sm-client-id=ID]
.SH "DESCRIPTION"
The \fBukui-wm\fP program starts the window manager configured by the user. If the user has not chosen a window manager it will launch a ukui compliant window manager.
.SH "USAGE"
The user can define his preferred window manager with the
.BI / org / ukui / desktop / session / required-components / windowmanager
dconf key. The value of this key should be the name of the desktop file of the desired window manager, without its \fB.desktop\fP extension. If this key is set to \fBukui-wm\fP, then \fBukui-wm\fP will simply look for an appropriate window manager. The user can also override the selection of a window manager by setting the \fBWINDOW_MANAGER\fP environment variable.
.PP
If the \fB\-\-default-wm\fP option is used, \fBukui-wm\fP will use \fBWINDOWMANAGER\fP as window manager if the \fBWINDOW_MANAGER\fP environment variable is not set and if the
.BI / org / ukui / desktop / session / required-components / windowmanager
dconf key does not define a specific window manager, or if the configured window manager cannot be found.
.PP
The \fB\-\-sm-client-id\fP option is translated to an appropriate option depending on which window manager will be started.
.SH "OPTIONS"
The following options are supported:
.TP
.B \-\-default-wm=WINDOWMANAGER
Define the default window manager to start if no window manager is configured, or if the configured window manager cannot be found.
.TP
.B \-\-sm-client-id=ID
Specify the session management \fIID\fP when connecting to the session manager.
.SH "ENVIRONMENT"
\fIukui-wm\fP uses the value of the \fBWINDOW_MANAGER\fP environment variable to let the user override the configured window manager.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at:
https://github.com/ukui/ukui-session-manager/issues 
.SH "AUTHORS"
.SS This Man Page has been updated for the UKUI Desktop Environment by:
yilei <yilei@kylinos.cn> (2016)
.SH "HISTORY"
.SS This Man Page has been updated for the MATE Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SS This Manual was originally written for gnome-session by:
.nf
Miguel de Icaza <miguel@helixcode.com> (2000)
Vincent Untz <vuntz@gnome.org> (2009-2010)
.fi
.SH "SEE ALSO"
.SS Further information may also be available at: http://wiki.ukui.org/
.P
.BR ukui-session-properties(1),
.BR ukui-session-save(1),
.BR ukui-session(1)
