.\" ukui-session-shortcuts manual page.
.\" (C) 2019, Tianjin KYLIN Information Technology Co., Ltd.
.\"
.TH UKUI-SESSION-SHORTCUTS 1 "11 February 2019" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
ukui-session-shortcuts\- Show the keyboard shortcuts.
.SH "SYNOPSIS"
.B ukui-session-shortcuts
.SH "DESCRIPTION"
.PP
The \fBukui-session-shortcuts\fP program can show the keyboard
shortcuts.
.SH "OPTIONS"
.TP
\fB\-\-display=DISPLAY\fR
X display to use.
.TP
\fB\-\-version\fR
Output version information and exit.
.TP
\fB\-\-show\fR
Show the keyboard shortcuts.
.TP
\fB\-?, \-h, \-\-help\fR
Print standard command line options.
.TP
\fB\-\-help\-all\fR
Print all command line options.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at:
https://github.com/ukui/ukui-session-manager/issues
.SH "AUTHORS"
handsome_feng <jianfengli@ubuntukylin.com>
.fi
.SH "SEE ALSO"
.SS Further information may also be available at: http://wiki.ukui.org/
.P
.BR ukui-session(1),
.BR ukui-session-save(1),
.BR ukui-wm(1)
